export const SET_MONTH_INDEX = "SET_MONTH_INDEX";
export const SHOW_REMINDER_MODAL = "SHOW_REMINDER_MODAL";
export const SET_REMINDER_DATE = "SET_REMINDER_DATE";
export const ADD_REMINDER = "ADD_REMINDER";
export const EDIT_REMINDER = "EDIT_REMINDER";
export const DELETE_REMINDER = "DELETE_REMINDER";
export const SET_SELECTED_REMINDER = "SET_SELECTED_REMINDER";
export const GET_WEATHER_FORECAST = "GET_WEATHER_FORECAST";
